version: '1.0'
name: deploy-demo
displayName: deploy-demo
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - master
stages:
  - name: stage-67109006
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 17.8.0
        commands:
          - '# 设置NPM源，提升安装速度'
          - yarn config set registry http://registry.npm.taobao.org/
          - ''
          - '# 执行编译命令'
          - yarn install && yarn build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
        caches:
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
