version: '1.0'
name: pipeline-20231026
displayName: pipeline-20231026
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-29aca982
    displayName: 编译
    strategy: naturally
    trigger: auto
    executor:
      - password-x
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 17.8.0
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npm.taobao.org/
          - ''
          - '# 执行编译命令'
          - npm install yarn
          - ''
          - yarn config set registry https://registry.yarnpkg.com
          - ''
          - yarn install
          - yarn build
          - ''
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
